generate_all:
	gleam run -m generate heroicons ../heroicons/src/24/outline ../src/heroicons/outline24.gleam
	gleam run -m generate heroicons ../heroicons/src/24/solid ../src/heroicons/solid24.gleam
	gleam run -m generate heroicons ../heroicons/src/20/solid ../src/heroicons/solid20.gleam
	gleam run -m generate heroicons ../heroicons/src/16/solid ../src/heroicons/solid16.gleam
